### DISCUSSION TITLE
Not able to connect to database when running in dockers

### DISCUSSION THREAD

**Discussion by affien70** [equinor/witsml-explorer#1744] [General]
Hi,
I'm strugling a bit to connect the back end to the database when running in dockers.
I have created 3 docker containers. witsmlexplorer-db, witsmlexplorer-frontend-dev and witsmlexplorer-api-dev.
I'm able to reach the front end gui but I can't save servers or read from DB.

But when I stopped the witsmlexplorer-api-dev container and started it localy using "dotnet" everything worked as it should. I was able to connect to Sitecom, save the server in DB and browse the WITSML.
So I guess i must have missconfigured something in my docker container? 

The first error message I get when reloading the front end is the following:
```
witsmlexplorer-api-dev       | [09:05:37 FTL] Something went wrong: System.InvalidOperationException: Unable to resolve service for type 'WitsmlExplorer.Api.Repositories.IDocumentRepository`2[WitsmlExplorer.Api.Models.Server,System.Guid]' while attempting to
 activate 'WitsmlExplorer.Api.Services.CredentialsService'.
```
I'm running all on my laptop, with Windows 11, .net 7.0 and Docker Desktop.
I would be glad to receive any hints on what I need to check to get this up and running in docker. It seems like the front end is talking to the back end, but there it stops.

Thanks.

Alf Ove Røyland
Wells Data Management Advisor
ConocoPhillips

**Comment by steinsiv** [comment]
Hi thanks for reaching out!

From the description it sounds to me like the API container lacks connection with the running MongoDb instance. 

If you are running something similar to the file `docker-compose.yml` under `Docker/Local` folder, it will only raise two containers with a shared network. If you then have MongoDb running separately as a container on the host with ports exposed, you need to use the `host.docker.internal` hostname for the API to be able to talk to the MongoDb instance on the host. Something like below for the `config.json` file. (spec here: [config.json](https://github.com/equinor/witsml-explorer/blob/main/Docker/README.md#configjson))

```  
"MongoDb": {
    "Name": "witsml-explorer-db",
    "ConnectionString": "mongodb://user:password@host.docker.internal"
```

In the second type of setup where you can run all three containers in the same network (and all three are defined as services in the same `docker-compose.yml` file) you will have to use the defined name in the dockerfile (like `api` and `web` are defined) instead of `host.docker internal`. Something like below (depending on service name for mongodb used in docker-compose)

```
"MongoDb": {
    "Name": "witsml-explorer-db",
    "ConnectionString": "mongodb://user:password@mongodb"

```

I hope this was helpful, but if the issue was not about connectivity and lies elsewhere, we can try to help locate the issue just let us know. We will then need your docker-compose setup and/or config.json without credentials so that we could try to replicate the error and find a solution.

**Reply by affien70** [reply]
Thanks Stein,
I'm fireing up the dockers from the following docker-compose.yml

```
version: '3.7'
services:
  api:
    build: .
    image: witsmlexplorer-api:latest
    container_name: witsmlexplorer-api-dev
    ports:
      - 5000:5000
    volumes:
      - ./config.json:/app/config.json:ro
      - ./ca-bundle.crt:/etc/ssl/certs/ca-bundle.crt:ro
    environment:
      - SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt      

  web:
    image: witsmlexplorer-frontend:latest
    container_name: witsmlexplorer-frontend-dev
    ports:
      - 3000:3000
      
  mongo:
    image: mongo:4.4.1
    container_name: witsmlexplorer-db
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=SomeUser
      - MONGO_INITDB_ROOT_PASSWORD=SomePassword
 ```

And my config.json looks like the following:

```
{
  "LogQueries": false,
  "AllowedHosts": "*",
  "Host": "http://localhost:27017",
  "MongoDb": {
    "Name": "witsml-explorer-db",
    "ConnectionString": "mongodb://SomeUser:SomePassword@localhost:27017"
  }
}
```

**Reply by steinsiv** [reply]
Hi thanks for the files. 

I think the main issue here was the url for the mongodb database pointing to `localhost:27017`. 
I tried to run locally the same files with some minor changes with success, if you could try adjusting with the `docker-compose.yml` and `config.json` like in the samples below and please let us know if that does not resolve the issue on your end.

### docker-compose.yml
```yml
version: '3.7'
services:
  api:
    image: witsmlexplorer-api:latest
    container_name: witsmlexplorer-api-dev
    ports:
      - 5000:5000
    volumes:
      - ./config.json:/app/config.json:ro
      - ./ca-bundle.crt:/etc/ssl/certs/ca-bundle.crt:ro
    environment:
      - SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt      
    depends_on:
      - database

  web:
    image: witsmlexplorer-frontend:latest
    container_name: witsmlexplorer-frontend-dev
    ports:
      - 3000:3000
    depends_on:
      - api
      
  database:
    image: mongo:4.4.1
    container_name: witsmlexplorer-db
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=SomeUser
      - MONGO_INITDB_ROOT_PASSWORD=SomePassword
```

### config.json
```json
{
  "MongoDb": {
    "Name": "witsml-explorer-db",
    "ConnectionString": "mongodb://SomeUser:SomePassword@database"
  },
  "Host": "http://localhost",
  "OAuth2Enabled": false
}

```
